language: go

go:
  - "1.11.2"

services:
  - docker

before_script: 
  - export VAULTDIR=$HOME/local/bin
  - mkdir -p $VAULTDIR
  - export PATH=$VAULTDIR:$PATH
  - curl https://releases.hashicorp.com/vault/0.11.5/vault_0.11.5_linux_amd64.zip -o $VAULTDIR/vault.zip
  - unzip $VAULTDIR/vault.zip -d $VAULTDIR

script: ./demo.sh
