language: go

go:
  - "1.11.2"

services:
  - docker

before_script: 
  - curl https://releases.hashicorp.com/vault/0.11.5/vault_0.11.5_linux_amd64.zip -o /usr/local/bin/vault.zip
  - sudo unzip /usr/local/bin/vault.zip

script: ./demo.sh
